name: QuickEconomy
version: '${project.version}'
main: net.derfla.quickeconomy.main
api-version: '1.20'
author: AffeKri
commands:
  balance:
    usage: /<command> <subcommand> <float> <player>
    description: See your balance or send coins to other players.
  bal:
    usage: /<command> <subcommand> <float> <player>
    description: See your balance or send coins to other players.
  quickeconomy:
    usage: /<command>
    description: Misc
