name: QuickEconomy
version: '${project.version}'
main: net.derfla.quickeconomy.main
api-version: '1.20'
author: AffeKri
commands:
  balance:
    usage: /<command> <subcommand> <float> <player>
    description: See your balance.
    permission: quickeconomy.balance
    permission-message: You do not have <permission>
  bal:
    usage: /<command> <subcommand> <float> <player>
    description: See your balance.
    permission: quickeconomy.balance
    permission-message: You do not have <permission>
  quickeconomy:
    usage: /<command>
    description: Misc
    permission: quickeconomy.quickeconomy
    permission-message: You do not have <permission>
